### ISSUE TITLE
monaural source is not supported (was java.lang.ArrayIndexOutOfBoundsException )

### ISSUE THREAD

**Issue by mckuhei** [umjammer/mp3spi#4]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream$DMAISObuffer.append(DecodedMpegAudioInputStream.java:292)
	at javazoom.jl.decoder.Obuffer.appendSamples(Obuffer.java:59)
	at javazoom.jl.decoder.SynthesisFilter.compute_pcm_samples(SynthesisFilter.java:1510)
	at javazoom.jl.decoder.SynthesisFilter.calculate_pcm_samples(SynthesisFilter.java:1550)
	at javazoom.jl.decoder.LayerIIIDecoder.decode(LayerIIIDecoder.java:324)
	at javazoom.jl.decoder.LayerIIIDecoder.decodeFrame(LayerIIIDecoder.java:219)
	at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147)
	at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:193)
	at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:136)
	at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:195)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1120)
	at ml.mckuhei.utils.AudioUtil.main(AudioUtil.java:77)
```

This is my test code:
```Java
	public static void main(String[] args) throws Exception {
		AudioInputStream audio = fromNetease(1440363337);
		audio = AudioSystem.getAudioInputStream(new AudioFormat(Encoding.PCM_SIGNED, 44100, 16, 1, 2, 44100, false) , audio);
		Clip c = AudioSystem.getClip();
		c.open(audio);
		c.start();
		Thread.sleep((long) (c.getFrameLength()/44100F)*1000L);
	}
```

**Comment by mckuhei** [comment]
Okay, I found fix way.
```Java
        public void append(int nChannel, short sValue) {
            byte bFirstByte;
            byte bSecondByte;
            if (m_bIsBigEndian) {
                bFirstByte = (byte) ((sValue >>> 8) & 0xFF);
                bSecondByte = (byte) (sValue & 0xFF);
            } else // little endian
            {
                bFirstByte = (byte) (sValue & 0xFF);
                bSecondByte = (byte) ((sValue >>> 8) & 0xFF);
            }
            if (nChannel==1&&m_anBufferPointers.length==1) { // mono channel
                int pointer = m_anBufferPointers[0];
                m_abBuffer[pointer] = (byte)((m_abBuffer[pointer]+bFirstByte) / 2);
                m_abBuffer[pointer + 1] = (byte)((m_abBuffer[pointer + 1] + bSecondByte) / 2);
            } else {
                m_abBuffer[m_anBufferPointers[nChannel]] = bFirstByte;
                m_abBuffer[m_anBufferPointers[nChannel] + 1] = bSecondByte;
                m_anBufferPointers[nChannel] += m_nChannels * 2;
            }
        }

**Comment by umjammer** [comment]
on my env

monaural mp3 works w/o modification

```shell
$ ffmpeg -i src/test/resources/test.mp3 -ac 1 src/test/resources/mono.mp3 
```

```java
        AudioInputStream in = AudioSystem.getAudioInputStream(MonoTest.class.getResourceAsStream("/mono.mp3"));
        AudioFormat inFormat = in.getFormat();
logger.info("In Format : " + inFormat.toString());
        AudioFormat outFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED,
                                                    inFormat.getSampleRate(),
                                                    16,
                                                    inFormat.getChannels(),
                                                    inFormat.getChannels(),
                                                    inFormat.getSampleRate(),
                                                    false);
logger.info("Out Format : " + outFormat.toString());
        AudioInputStream out = AudioSystem.getAudioInputStream(outFormat, in);;
        Clip c = AudioSystem.getClip();
        c.open(out);
        c.start();
        Thread.sleep((long) (c.getFrameLength() / 44100.) * 1000);
```

**Comment by mckuhei** [comment]
> 

Please test this file.
This is the problem of converting two channels to mono。
[audio.zip](https://github.com/umjammer/mp3spi/files/7587384/audio.zip)

**Comment by mckuhei** [comment]
> Okay, I found fix way.
> 
> ```java
>         public void append(int nChannel, short sValue) {
>             byte bFirstByte;
>             byte bSecondByte;
>             if (m_bIsBigEndian) {
>                 bFirstByte = (byte) ((sValue >>> 8) & 0xFF);
>                 bSecondByte = (byte) (sValue & 0xFF);
>             } else // little endian
>             {
>                 bFirstByte = (byte) (sValue & 0xFF);
>                 bSecondByte = (byte) ((sValue >>> 8) & 0xFF);
>             }
>             if (nChannel==1&&m_anBufferPointers.length==1) { // mono channel
>                 int pointer = m_anBufferPointers[0];
>                 m_abBuffer[pointer] = (byte)((m_abBuffer[pointer]+bFirstByte) / 2);
>                 m_abBuffer[pointer + 1] = (byte)((m_abBuffer[pointer + 1] + bSecondByte) / 2);
>             } else {
>                 m_abBuffer[m_anBufferPointers[nChannel]] = bFirstByte;
>                 m_abBuffer[m_anBufferPointers[nChannel] + 1] = bSecondByte;
>                 m_anBufferPointers[nChannel] += m_nChannels * 2;
>             }
>         }
> ```

Okay, I tested. Doesn't work.

**Comment by umjammer** [comment]
i got it

*input stereo, output monaural* is the problem.

**Comment by umjammer** [comment]
i found mono -> stereo coversion has problem also.

---

i made `mp3spi` reject monaural <-> stereo conversion. see cfb5a0d

because i think monaural <-> stereo conversion is not `mp3spi`'s responsibility.
Java classes stands on [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle),
so that `mp3spi` shouldn't have such a conversion capability.

[`toritonus-remaining`](https://github.com/umjammer/tritonus/blob/5342e8ea900e73b1b6598115f2209d515f6e571a/tritonus-remaining/src/main/java/org/tritonus/sampled/convert/PCM2PCMConversionProvider.java) has stereo <-> monaural conversion provider, we should use this.
(`toritonus-remaining` is already included by `mp3spi`)

please convert using 2 step conversion like this,

https://github.com/umjammer/mp3spi/commit/cfb5a0d61a9a25f65bcbc4cf0962c6da7bb6221a#diff-ffa51c04ecbf8858d94423c565028110ef6b7ba0b1d12903dbb6292ee9c236b8R87-R115

---

i agree two step conversion is inconvenience.
it should be done automatically.

[`toritonus-remaining`](https://github.com/umjammer/tritonus/blob/5342e8ea900e73b1b6598115f2209d515f6e571a/tritonus-remaining/src/main/java/org/tritonus/sampled/convert/SmartFormatConversionProvider.java) seems to try to do it.
but it doesn't work now (causes stack overflow).
i wish somebody would fix and [complete it](https://github.com/umjammer/vavi-sound-sandbox/blob/master/src/main/java/vavi/sound/sampled/misc/AutoWiredFormatConversionProvider.java).

---

anyway @mckuhei, thank you for your report 😸.

**Comment by mckuhei** [comment]
Oh thanks
